var CONSTANTS = {};

//LIMITS
CONSTANTS.JSHREAD_KEYS_MAX = 64;
CONSTANTS.PTHREAD_STACK_MIN = 0;
CONSTANTS.PTHREAD_THREADS_MAX = 2019;

//SHARED TYPES
CONSTANTS.FLOAT_64 = 0;

module.exports = CONSTANTS;
